# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'wastenot' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for wastenot
  pod 'React', path: '../node_modules/react-native', :subspecs => [
  'Core',
  'RCTActionSheet',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket'
]

# when not using frameworks  we can do this instead of including the source files in our project (1/4):
# pod 'react-native-maps', path: '../../'
#	pod 'react-native-google-maps', path: '../../'  # <~~ if you need GoogleMaps support on iOS

# when not using frameworks  we can remove this line (2/4):
  pod 'GoogleMaps'

  target 'wastenotTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# Auth0 Lock

pod 'Lock', '~> 1.26'
pod 'Lock/TouchID'
pod 'Lock/SMS'
pod 'Lock/Email'
